### PR TITLE
fix: refactor aggregation pipeline.

### LINKED ISSUE #134: EPSS Score is showing `null` in Analytic Report
**Describe the bug**

The EPSS enrichment task tags Vulnerabilities with an EPSS Score if one can be determined. This field should be exported to the Analytic report and available for query. It shows up as a json `null` for all records.

**To Reproduce**
Query the data for epssScore != 'null'

**Expected behavior**
Should receive results.

### PR DESCRIPTION
**Pull request by DerekStrickland**
## Summary

This PR makes improvements and logic corrections to the SDL aggregation pipeline.

### Fixed

- Fixed an issue resolving EPSS scores - Closes #134 

### Changed

- Made improvements to the aggregation pipeline in terms of both performance and readability
- Moved CMS specific daily export functionality from `cli` to `extensions/cms`.
- Created all associated tasks and services to `extensions/cms`.

### Removed

- CMS specific Fisma logic from `core/services/analytics/sboms/service`.

## How to test

- Start the devenv
- From the root of repo run `cargo test --package harbor-cms --lib tasks::export::tests::can_run -- --ignored --exact`
- Review the output json documents in `/tmp/harbor-debug/extensions/export` on your local file system

### CODE REVIEW

File: extensions/cms/src/tasks/export.rs [hunk 1]
```diff
@@ -0,0 +1,452 @@
...
+                "_id": "",
+                "purls": {
+                  "$push": {
+                    "purl": "$purl"}
+                    }
+                }
+            }
+        )));
+
+        match pipeline.execute_on("Package").await {
```
Comment (qtpeters) [inline extensions/cms/src/tasks/export.rs:126]: One improvement I can see here is that we could be using a type rather than a String to specify the collection we want to execute on.  If you are already in this code and it's not too off the grid with respect to the purpose of the ticket, refactoring the api here to be like: 
`pipeline.execute_on::<Package>()` ensures that the collection is, in fact a real collection, makes accidentally misspelling the name of the collection  impossible.  It also makes it easy to rename the collection if necessary because it's only a single refactor of the struct used to rename the Mongo document and we won't accidentally leave the old name of the Document here.

File: extensions/cms/src/errors.rs [hunk 2]
```diff
@@ -6,6 +6,9 @@ pub enum Error {
     /// Configuration error.
     #[error("config: {0}")]
     Config(String),
+    /// Export provider error.
+    #[error("export provider: {0}")]
+    Export(String),
```
Comment (qtpeters) [inline extensions/cms/src/errors.rs:11]: There are no uses of this Error on your branch.  Do we need it?

File: extensions/cms/src/tasks/export.rs [hunk 3]
```diff
@@ -49,9 +49,14 @@ impl TaskProvider for ExportTask {
         self.update(task).await?;
 
         println!("==> processing {} sboms for detail report", task.count);
+        let mut iteration = 0;
 
         for purl in primary_purls {
-            println!("==> generating detail report for purl {}", purl);
+            iteration += 1;
```
Comment (qtpeters) [inline extensions/cms/src/tasks/export.rs:55]: Do you need this extra iterator?  You can use this variation of the for loop instead:

```
    for (i, el) in list.iter().enumerate() {
        println!("The current element is {}", el);
        println!("The current index is {}", i);
    }
    ```

**Review by qtpeters — COMMENTED** [review]
Looks good so far!  Check out the logging in the pipeline.  We still have a lot of extra logging in there from debugging the Pipeline erlaier.

File: extensions/cms/src/tasks/export.rs [hunk 4]
```diff
@@ -0,0 +1,452 @@
...
+            .await
+        {
+            Ok(path) => Ok(Some(path)),
+            Err(e) => Err(Error::Analytic(format!(
+                "export::export_by_purl::write::{}",
+                e
+            ))),
+        }
+    }
+}
```
[the remark this answers is not in the document]
Comment (DerekStrickland) [reply extensions/cms/src/tasks/export.rs:417]: I suspect the "rightest" answer is to export/transform to a more relational model for analytics purposes and not query the object collections. But that is a much larger effort. Taking mental notes thought. :)

File: extensions/cms/src/tasks/export.rs (hunk 1 above)
Comment (DerekStrickland) [reply extensions/cms/src/tasks/export.rs:127]: I started doing this and quickly determined it was more involved that I'd like given the urgency of the related EPSS issue, so I'm punting on that for now.

File: extensions/cms/src/errors.rs (hunk 2 above)
Comment (DerekStrickland) [reply extensions/cms/src/errors.rs]: Good catch.  Removed.

File: extensions/cms/src/tasks/export.rs (hunk 3 above)
Comment (DerekStrickland) [reply extensions/cms/src/tasks/export.rs:55]: ahh that is an improvement.  Done.

File: extensions/cms/src/commands/export.rs
[the remark this answers is not in the document]
Comment (DerekStrickland) [reply extensions/cms/src/commands/export.rs:1]: That was a big end of day oops.  Fixed.

File: extensions/cms/src/tasks/export.rs (hunk 1 above)
Comment (qtpeters) [reply extensions/cms/src/tasks/export.rs:127]: :+1:

File: extensions/cms/src/tasks/export.rs (hunk 4 above)
[the remark this answers is not in the document]
Comment (qtpeters) [reply extensions/cms/src/tasks/export.rs:418]: Nice! Sounds good

File: extensions/cms/src/commands/export.rs
[the remark this answers is not in the document]
Comment (qtpeters) [reply extensions/cms/src/commands/export.rs:1]: All good!

**Review by qtpeters — APPROVED** [review]
Test passed on my machine: :shipit:
